// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CharacterShadowsMZ","status":true,"description":"(v.1.0) Display shadows under the player or events on the map.","parameters":{"sImage":"Shadow1","sOffset":"5"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
